### ISSUE TITLE
Activation of Snaps causes unsmoothed visual jitter

### ISSUE THREAD

**Issue by ky000** [lawnjelly/smoothing-addon#42]
With the new approach, not using TopLevel to solve issues in Ysort, I noticed that smoothing doesn't seem to work when snap options are active, such as Snap vertices and transformations. Previously, with Top Level, the jitter was resolved. Now, it seems that it's no longer rounding the sprite's position and causing visual jitter. I tested this on version 4.x. ~It seems that without top level, there might be some limitation, perhaps?

**Comment by ky000** [comment]
I will detail below the project settings and provide a demonstration video:
![image](https://github.com/lawnjelly/smoothing-addon/assets/81387545/84ab68a6-5859-4675-ad36-3ed3a292f595)
![image](https://github.com/lawnjelly/smoothing-addon/assets/81387545/1ccd0fdf-024b-4f31-a928-1c5ce94d061f)
![image](https://github.com/lawnjelly/smoothing-addon/assets/81387545/3b00b963-3c2d-494b-9418-d051ab6b37df)


https://github.com/lawnjelly/smoothing-addon/assets/81387545/91f635f9-bb6b-454c-a376-73c6c8756612

**Comment by lawnjelly** [comment]
Ah yes this is interesting. I'm not super familiar with the snapping in 4.x, but it could be the snapping is having trouble coping with the math going on when you have a smoothing node as a child of the node you are moving.

There are still some issues afaik with the core snapping in 4.x but it will be good if you can work around these.

So two options:
1) I can easily add a toggle to the smoothing node where it can do the old behaviour (of toplevel). The only downside is that in this mode you will have the problems with y sort and visibility back.
2) I suspect that the snapping might work better if you don't make the smoothing node a direct child of the target, i.e. put it on a separate branch, as was recommended when we first introduced the addon. (This might be worth trying to see if it cures the problem, even if less convenient).

If you can create a small minimum reproduction project I might be able to pin down better what is going on (maybe we won't need these workarounds).

**Comment by ky000** [comment]
> Ah yes this is interesting. I'm not super familiar with the snapping in 4.x, but it could be the snapping is having trouble coping with the math going on when you have a smoothing node as a child of the node you are moving.
> 
> There are still some issues afaik with the core snapping in 4.x but it will be good if you can work around these.
> 
> So two options:
> 
> 1. I can easily add a toggle to the smoothing node where it can do the old behaviour (of toplevel). The only downside is that in this mode you will have the problems with y sort and visibility back.
> 2. I suspect that the snapping might work better if you don't make the smoothing node a direct child of the target, i.e. put it on a separate branch, as was recommended when we first introduced the addon. (This might be worth trying to see if it cures the problem, even if less convenient).
> 
> If you can create a small minimum reproduction project I might be able to pin down better what is going on (maybe we won't need these workarounds).



Here's a little demo! You can run the main scene "mapManager", if you want to change the player's node hierarchy it is in "visual.tscn" 

[Project.zip](https://github.com/lawnjelly/smoothing-addon/files/12732050/Project.zip)



I tested it on a different branch and I didn't notice any difference

**Comment by ky000** [comment]
And it can come with a small problem, when you change the hierarchy you need to indicate the animation node again to the code. Just access "heroi.tscn" and indicate animationtree to it. a short video to help. Any feedback will be welcome. Thanks 🙂😂


https://github.com/lawnjelly/smoothing-addon/assets/81387545/24ac7ca1-03f2-4fd6-9b22-94b88e441398

**Comment by lawnjelly** [comment]
Testing the MRP with and without `toplevel` set, it seems there is a subtle difference, the parts of the model seem to be snapped _as one_ with toplevel set, and without it they are snapped individually, which leads to a strange blancmange effect where the body parts jitter amongst themselves.

The problematic setting is `snap_2d_vertices_to_pixel`, which is GPU snapping. This is something I'll have to deal with eventually with 4.x doing core physics interpolation. Luckily core interpolation is able to do a much more sensible path.

The issue in the scene tree without using toplevel, is that the global transforms of the parent node are inherited by the child, and thus the global transform of the smoothing node must be done _in relation_ to the parent, rather than in global space (which is more numerically stable). Core interpolation introduces a new mode for canvas items where they can be used in global space.

However for the smoothing addon, which will be used prior to this new mode, global transform of smoothing nodes (without toplevel) is done by first _undoing_ the global transform of the parent. This means the local transform of the smoothing node is quite variable, and also subject to float error. This may not be seen with regular use, but can upset the snapping as snapping has distinct floating point _borders_.

So for now I'll probably either recommend not to use GPU snapping in this scenario, or to set a `toplevel` bool on the smoothing node. I'll add this now, it should be pretty simple, and upload a new version to the repository.

**Comment by lawnjelly** [comment]
> And it can come with a small problem, when you change the hierarchy you need to indicate the animation node again to the code. Just access "heroi.tscn" and indicate animationtree to it. a short video to help. Any feedback will be welcome. 

Does this occur without the smoothing addon? Maybe this is a general engine bug?

**Comment by lawnjelly** [comment]
Let me know if the new `toplevel` mode in 1.2.1 fixes this for you.

**Comment by ky000** [comment]
> > And it can come with a small problem, when you change the hierarchy you need to indicate the animation node again to the code. Just access "heroi.tscn" and indicate animationtree to it. a short video to help. Any feedback will be welcome.
> 
> Does this occur without the smoothing addon? Maybe this is a general engine bug?

This is expected behavior. I indicate where the animation nodes are when the hierarchy is changed the position changes a little. I think it's more the code. It's not a problem; 

Yes, with Toplevel it now solves it completely... but then I return to the scenario of being left without y-sort. Maybe I should use a custom Ysort? like using Z index for now or something like that. , if I deactivate "snap vertices" and transform there is this problem of jitter in the fitting of the body part. So, the ideal would be to use the addon with TopLevel

**Comment by lawnjelly** [comment]
Yes y-sort with `toplevel` is kind of tricky, because `toplevel` basically breaks the scene tree in the `VisualServer`, and attaches the node to the root instead of the parent. It seems designed for modal dialog boxes and tooltips, rather than this scenario.

What we really want, is a way of parenting a `CanvasItem` such that it ignores the parent transform, and applies the local transform in global space. That way, y-sorting and visibility would "just work" :tm: .

This is actually what I had to implement in core for core 2D interpolation. So it is chicken egg problem, the problem will be solved, when 4.x has core interpolation. But by that time, you will no longer need the addon. :slightly_smiling_face: 

This does suggest maybe I'm better off spending the time implementing it properly by pushing ahead with the core physics interpolation for 4.x, rather than spending too long hacking the addon.

**Comment by ky000** [comment]
> Yes y-sort with `toplevel` is kind of tricky, because `toplevel` basically breaks the scene tree in the `VisualServer`, and attaches the node to the root instead of the parent. It seems designed for modal dialog boxes and tooltips, rather than this scenario.
> 
> What we really want, is a way of parenting a `CanvasItem` such that it ignores the parent transform, and applies the local transform in global space. That way, y-sorting and visibility would "just work" ™️ .
> 
> This is actually what I had to implement in core for core 2D interpolation. So it is chicken egg problem, the problem will be solved, when 4.x has core interpolation. But by that time, you will no longer need the addon. 🙂
> 
> This does suggest maybe I'm better off spending the time implementing it properly by pushing ahead with the core physics interpolation for 4.x, rather than spending too long hacking the addon.
> 
> > if I deactivate "snap vertices" and transform there is this problem of jitter in the fitting of the body part.
> 
> Note that snapping vertices and transform is completely different in 4.x. Transform is done on CPU, vertices is done on GPU. When I tested it, snapping vertices caused problems, but not snapping transform.

Yes. In fact, with the toplevel approach, I don't even need to enable "snap vertices", toplevel already seems to resolve the displaced pixels. Just like you mentioned, treating them as "one", not separately. I'm already happy with at least understanding the root of the problem. Now it's time to wait until this is supported correctly as you mentioned. Thanks for all the support! I'll keep an eye on this in the future ^^

Vertices off 
Toplevel on: 
![image](https://github.com/lawnjelly/smoothing-addon/assets/81387545/1221caff-fccf-4175-a741-6253dd9cca62)

Vertices off 
Toplevel off: 
![image](https://github.com/lawnjelly/smoothing-addon/assets/81387545/521ae7b4-a1dd-4b86-ba15-934a3f515eed)
