### ISSUE TITLE
Jitter with moving player

### ISSUE THREAD

**Issue by zmnpl** [lawnjelly/smoothing-addon#48]
Hi, so as mentioned in my other issue I seem to have Jitter (I think) with a moving player. 

Here is a video of what I mean. The sprite seems unsharp, almost filtered. Though it is not filtered. It looks like the position is slightly changing really fast. At the end of the video, I think from second 12 on you can see suddenly after moving the character a bit, the sprite gets sharp (actually, when starting the scene it's sharp and becomes unsharp after movement). This happens both when using toplevel and the default mode as shown on the screenshots below*. 
https://github.com/lawnjelly/smoothing-addon/assets/9001667/3a04a6cf-4fd1-4fa9-a761-c02a3b01cc75

Any suggestion to prevent this?

*Tried these setups:
![Screenshot_20231031_085741](https://github.com/lawnjelly/smoothing-addon/assets/9001667/43ec9736-2cf4-4a9a-9357-6941a9ce7afd)

![Screenshot_20231031_090404](https://github.com/lawnjelly/smoothing-addon/assets/9001667/343ec103-395b-4192-a374-8430aa1e3f8f)

This would be the project I am testing this with:
[testproject.zip](https://github.com/lawnjelly/smoothing-addon/files/13213687/testproject.zip)

**Comment by lawnjelly** [comment]
I'm not 100% sure on what you were referring to, but it looks like texture filtering which is a general engine thing rather than to do with the addon. i.e. If you move a sprite to a subpixel position you may get filtering artifacts depending on how you have the engine setup.

I'm not very familiar with Godot 4 as I mostly work on Godot 3.x so you may be better asking in some community channels (e.g. discord?).

Jitter BTW is described here, I can't see any obvious jitter in your project:
https://docs.godotengine.org/en/stable/tutorials/rendering/jitter_stutter.html#:~:text=There%20can%20be%20many%20causes,is%20different%20from%2060%20Hz.

**Comment by zmnpl** [comment]
Derp, I think you are right. Switching the texture filter to nearest helps.
Still thanks for going through my non-issue!
