### ISSUE TITLE
Camera stuttering with rigidbody 3d

### ISSUE THREAD

**Issue by p1ckLL** [lawnjelly/smoothing-addon#56]
I have a simple script that applies addforce to a rigidbody3d, and my camera seems to be struggling to keep up. I tried this addon but have no had any luck so far.

this is what my code looks like:
```
func _input(event):     
	if event is InputEventMouseMotion:      
		rotate_y(-deg_to_rad(event.relative.x * MOUSE_SENS))
		$Smoothing/Head.rotate_x(-deg_to_rad(event.relative.y * MOUSE_SENS))
		
		var head_rotation = $Smoothing/Head.rotation_degrees;
		head_rotation.x = clamp(head_rotation.x, -90, 90);
		$Smoothing/Head.rotation_degrees = head_rotation;
```

And here is an image of my hierarchy:
![image](https://github.com/user-attachments/assets/33619174-8dac-4536-a2c3-a916243d3432)

**Comment by lawnjelly** [comment]
Trying to apply transforms manually on top of smoothed transforms can be quite tricky, there are a number of gotchas, especially with cameras.

This would probably need an MRP to investigate.

**Comment by p1ckLL** [comment]
Hello, sorry for the delay. Here is an MRP for my project!
eva.tscn is what you can use for testing

Thanks!

[MRP.zip](https://github.com/user-attachments/files/16260871/MRP.zip)

**Comment by lawnjelly** [comment]
I'm trying the MRP, and reducing tick rate to 10tps (to show interpolation problems).

> my camera seems to be struggling to keep up

Can you elaborate on the problem?
Is the problem you are describing involving pressing the thrusters, or just the rotation of the camera with the mouse?

Have you tried disabling the interpolation by turning off the `enabled` flag in the smoothing node? (i.e. is the problem anything to do with the smoothing node?)

**Comment by p1ckLL** [comment]
When thrusting around, my game just stutters and i can move my camera around but my body doesnt keep moving. The reason i think the camera is the problem is because if i disable the camera movement code, the physics stuttering disappears. Here is a video of what i am describing:
https://streamable.com/5d3gvt

**Comment by lawnjelly** [comment]
There are a number of problems I believe, before we get to smoothing node.

One initial thing is you shouldn't be changing rotation of physics objects directly (especially outside the physics tick), you should be applying forces, and angular velocity. Applying transform directly will screw up the physics simulation.

For first person cameras often the camera yaw and pitch is handled above the rigid body, rather than on the rigid body.

EDIT: Yes, can confirm this seems to be interacting with using `apply_force()` every tick.

I'll see if we can come up with some recommendations to fix.

Also I would recommend storing yaw and pitch internally and setting these directly, rather than using `rotate_y()` type functions, which will lead to float error. (Actually no scratch that, you may get away with it because in freeform 3D you have no reference up, so you may need to use relative rotations in some form.)

EDIT: Yes, can confirm, creating a node below the smoothing node as a parent for everything, and using this for yaw instead of the rigid body fixes a lot of issues / lag.

**Comment by lawnjelly** [comment]
Here is fixed scene:
![player_scene](https://github.com/user-attachments/assets/996d3659-1b1b-43f0-8c55-f75cf5977c61)

Note there is a `yaw` Node3D which is where I'm now applying yaw (and pitch). Mouse control should be below the smoothing node because it shouldn't be smoothed.

Here the smoothing node is off, because your major bugs are nothing to do with smoothing.

You have some choices to make:

For game such as this, you could use a sphere instead of capsule. This means you don't need to worry about applying mouse input to the collision shape, which is where things get hairy.

If you do want the mouse input to affect the collision shape rotation, you will probably get at best, laggy response, because physics only responds on physics ticks.

If you are using a sphere and handling the yaw and pitch below the rigid body in the tree, then you will need to back calculate the direction for thrust to be applied (or maybe get the direction of the child nodes directly, and use this).

Typically for 1st person games the approach I've mentioned is used, store yaw and pitch yourself, and set the rotation directly. For space games with no up, you do need to use relative rotations. I would still store these in your own gdscript personally, but you might be able to get away with relying on the node transform.

How you compromise the need for responsive mouse movement, and the need to align rigid body rotation is up to you to decide for your game design.

Anyway hope that gets you started, there are no problems here so far related to smoothing node as far as I can see.

(Also don't put collision shapes under smoothing node, they should be child of rigid body).

**Comment by p1ckLL** [comment]
Thank you so much! I appreciate the quick responses tremendously. Thanks for the addon!!
