### ISSUE TITLE
Unable to use camera node in 3d along with smoothing node

### ISSUE THREAD

**Issue by Instincts9o2** [lawnjelly/smoothing-addon#7]
**Scene causing the problem with smoothing node added:-**

![prob_scene](https://user-images.githubusercontent.com/28779559/90334532-e9bce200-dfeb-11ea-9ddb-92f9ca9c61b1.png)

**Script attached to Player node (Kinematic Body):-**
```
extends KinematicBody
var constant_speed: Vector3 = Vector3(0, 0, -10)
func _physics_process(_delta):
    constant_speed = move_and_slide(constant_speed)
```

**Output:-**

![prob_runtime_trim](https://user-images.githubusercontent.com/28779559/90334540-f7726780-dfeb-11ea-9051-fea78f0d42f0.gif)

**Expected Output**:-

![fine_runtime_trim](https://user-images.githubusercontent.com/28779559/90334543-fc371b80-dfeb-11ea-9fd4-8ea762890d99.gif)

As seen in the first output gif the player moves away from the camera which it shouldn't. The expected output is what it should look like. 

**The following scene without the smoothing node works as expected and gives the expected output:-**

![fine_scene](https://user-images.githubusercontent.com/28779559/90334536-f0e3f000-dfeb-11ea-9694-01f1c72bbfdc.png)

**Comment by lawnjelly** [comment]
First thing to try is to make the smoothing node separate from the physics:
```
PlayerPhysics(rigidbody)
    CollisionShape
Player(smoothingnode)
    Camera
    Skeleton
        unamed
```
I've seen a few people make the smoothing node a child of the physics they are linked to. This can sometimes work, but it is very recommended against. I need to emphasize this more in the docs.

The reason being is the smoothing node will interpolate between two target positions, usually in global space, but by putting them below a moving node, the parent movements will be applied to the child AS WELL as the transform for smoothing. This can lead to jitter or worse.

I'm not sure this is the answer to your problem here, I'll try and replicate your problem, but it is worth a go. I'll also modify the docs again to try and make it more clear (this came up recently with another user with similar problem).

**Comment by lawnjelly** [comment]
I've actually just been trying to replicate this but can't get the problem to occur. Would you be able to zip up the test project and drag it into the issue so I can try it?

While I highly recommend putting the visual representation on a different branch to the physics rep (see the updated docs), I'm not sure it is causing the problem here. It could be something in the setup of the skeleton.

**Comment by Instincts9o2** [comment]
> Yes I've got it replicating. Can confirm that the solution is to make sure the SmoothingNode is NOT a child of the physics rep.
> 
> Actually this has made me realise I may be able to detect the situation of assigning the smoothing node to a parent or grandparent, and print an error messagebox, and how to fix it. +1
> 
> I'll see if this is possible and modify the addon.

Yep it worked. Your addon has been a huge help. Thank you for your time <3.

**Comment by lawnjelly** [comment]
No problem, it's great to get feedback. :grin:
